version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sena_test_backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sena_test_frontend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

networks:
  default:
    driver: bridge
